### PR TITLE
Fix backside z-fighting

### PR DESCRIPTION
**Pull request by mxcop**
Hey again 👋 I fixed the issue #10 

I saw an issue for webkit where the backside and frontside of the card were fighting for the front row seat :D

I managed to fix it using a simple transform *(also tested it on my safari)*
I cannot see any space between the cards at all even with this translation so I think it should be fine.

<sub>Maybe it's more of a temporary fix nevertheless this makes the safari experience a lot better :D</sub>
<sub>I forgot to pull main before commiting, hence the merge commit (will try to remember this for the future)</sub>

### CODE REVIEW

**Comment by canpoyrazoglu** [comment]
Just tested on MacBook Pro (Safari 16.1). The main issue is gone!

There is a slight glitch in Safari on V, V Star, Trainer Holo, and Trainer Gallery cards which manifests like a division of the effect both horizontally and vertically (it's hard to explain with words, see below video) that isn't present in Chrome but I confirm that the main problem is gone and despite the glitch I can personally say its totally usable on Safari now 🎊


https://user-images.githubusercontent.com/4348413/199142529-8fb00b4f-0933-4826-af73-b16d0e4d5654.mov

(Related: #10)

**Comment by mxcop** [comment]
> Just tested on MacBook Pro (Safari 16.1). The main issue is gone!
> 
> There is a slight glitch in Safari on V, V Star, Trainer Holo, and Trainer Gallery cards which manifests like a division of the effect both horizontally and vertically (it's hard to explain with words, see below video) that isn't present in Chrome but I confirm that the main problem is gone and despite the glitch I can personally say its totally usable on Safari now 🎊
> 
>  almost.mov 
> (Related: #10)

I think this might be fixable using ``-webkit-gradient`` on top of normal gradients.
<sub>Haven't tried it yet</sub>

**Comment by simeydotme** [comment]
Thanks both, yes I see the same. 

It looks like the `background-image` layers are not stacked / blended correctly... as well as the `background-position` in Safari is not behaving the same as Chrome/FF ... will need to a spend a bunch of time debugging this in Safari. But it looks achievable after the zIndex resolution :) 

Just need a bit of time on it.

**Comment by simeydotme** [comment]
> I think this might be fixable using `-webkit-gradient` on top of normal gradients.

Not sure about this, gradients (linear/radial) have been pretty much supported since like 2014/15 on all browsers. And that syntax was not supporting full gradient spec as I remember... so it probably cannot handle the craziness these effects need 😆

**Pull request merged**
